#!/usr/bin/env node
/**
 * Regenerate the reference tables in docs/ from the registry and the catalog.
 *
 * Hand-written compatibility tables rot the day a vendor ships a release, and a
 * wrong one sends people into a failing session. These are generated instead.
 *
 * Usage: npm run build && npm run docs
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

/** Windows absolute paths are not valid ESM specifiers; file:// URLs are. */
const load = (...segments) => import(pathToFileURL(path.join(root, 'dist', ...segments)).href);
const { AGENTS } = await load('agents', 'index.js');
const { loadBundledCatalog, build } = await load('catalog.js');
const { negotiateWire, WIRE_LABELS } = await load('resolve.js');
const { PROVIDER_OVERLAY } = await load('data', 'overlay.js');

const catalog = build(loadBundledCatalog(), 'bundled');
const stamp = new Date().toISOString().slice(0, 10);
const banner = `<!-- Generated by scripts/gen-docs.mjs on ${stamp}. Do not edit by hand. -->`;

// ---------------------------------------------------------------- agents.md

const featured = [
  'openrouter',
  'deepseek',
  'zai',
  'moonshotai',
  'groq',
  'openai',
  'anthropic',
  'ollama',
]
  .map((id) => catalog.providers.find((provider) => provider.id === id))
  .filter(Boolean);

const agentRows = AGENTS.map((agent) => {
  const usable = catalog.providers.filter((provider) => negotiateWire(agent, provider));
  return `| \`${agent.id}\` | [${agent.name}](${agent.homepage}) | ${agent.wires
    .map((wire) => WIRE_LABELS[wire])
    .join(', ')} | ${usable.length} | ${agent.description} |`;
});

const matrixHeader = `| agent | ${featured.map((provider) => provider.id).join(' | ')} |`;
const matrixDivider = `| --- | ${featured.map(() => '---').join(' | ')} |`;
const matrixRows = AGENTS.map(
  (agent) =>
    `| \`${agent.id}\` | ${featured
      .map((provider) => (negotiateWire(agent, provider) ? 'yes' : '-'))
      .join(' | ')} |`,
);

const agentsDoc = `# Agents

${banner}

Every agent anyagent can launch, the protocol it speaks, and how many of the
${catalog.providers.length} catalogued providers can drive it.

| id | agent | speaks | providers | description |
| --- | --- | --- | --- | --- |
${agentRows.join('\n')}

Aliases: ${AGENTS.filter((agent) => agent.aliases?.length)
  .map((agent) => `\`${agent.id}\` (${agent.aliases.map((alias) => `\`${alias}\``).join(', ')})`)
  .join(', ')}.

## Compatibility

An agent can only use a provider that speaks its protocol. Run
\`anyagent compat\` for this table against your live catalog, or
\`anyagent providers --agent <id>\` for the full list.

${matrixHeader}
${matrixDivider}
${matrixRows.join('\n')}

## Installing

anyagent offers to run the vendor's own install command when an agent is missing,
after asking. To do it yourself:

${AGENTS.map(
  (agent) =>
    `- **${agent.name}** - ${
      agent.install.command ? `\`${agent.install.command.join(' ')}\`` : 'see docs'
    } (${agent.install.url})`,
).join('\n')}
`;

fs.writeFileSync(path.join(root, 'docs', 'agents.md'), agentsDoc);

// ------------------------------------------------------------- providers.md

const anthropicCapable = catalog.providers
  .filter((provider) => provider.baseUrl.anthropic)
  .map((provider) => {
    const source = PROVIDER_OVERLAY[provider.id]?.anthropicSource;
    return `| \`${provider.id}\` | ${provider.name} | ${provider.baseUrl.anthropic} | ${
      source ?? 'catalog'
    } |`;
  });

const responsesCapable = catalog.providers
  .filter((provider) => provider.baseUrl['openai-responses'])
  .map((provider) => {
    const source = PROVIDER_OVERLAY[provider.id]?.responsesSource;
    return `| \`${provider.id}\` | ${provider.name} | ${provider.baseUrl['openai-responses']} | ${
      source ?? 'catalog'
    } |`;
  });

const unsupported = [...catalog.unsupported.entries()]
  .filter(([, reason]) => !reason.startsWith('No HTTP endpoint'))
  .map(([id, reason]) => `| \`${id}\` | ${reason} |`);

const providersDoc = `# Providers

${banner}

anyagent knows **${catalog.providers.length} providers** and
**${[...catalog.models.values()].reduce((total, list) => total + list.length, 0)} models**,
from the [models.dev](https://models.dev) catalog plus a curated overlay.

\`\`\`bash
anyagent providers                 # browse them all
anyagent providers --agent claude  # only those a given agent can use
anyagent models kimi               # search models
anyagent update                    # refresh from models.dev
\`\`\`

Anything not listed still works with an explicit endpoint:

\`\`\`bash
anyagent opencode --base-url https://my-gateway.internal/v1 -m my-model
\`\`\`

## Anthropic-compatible providers

These serve an Anthropic Messages endpoint, which is what **Claude Code** needs.
The source column records how the endpoint was established: \`probe\` means the
route was confirmed to exist, \`docs\` means the vendor publishes it but the host
authenticates before routing so a probe cannot distinguish it, and \`catalog\`
means models.dev already described the provider as Anthropic-native.

| id | provider | endpoint | source |
| --- | --- | --- | --- |
${anthropicCapable.join('\n')}

## OpenAI Responses providers

These serve \`/responses\`, which is what **Codex** and **Copilot CLI** need.
Codex removed \`wire_api = "chat"\`, so a chat-only provider cannot drive it.

| id | provider | endpoint | source |
| --- | --- | --- | --- |
${responsesCapable.join('\n')}

## Everything else

Every other catalogued provider serves OpenAI Chat Completions and works with
OpenCode, Droid, DeepSeek Harness, Pi, OpenClaw, Hermes, Cline, Qwen Code and Pool.

## Local runtimes

| id | endpoint | notes |
| --- | --- | --- |
| \`ollama\` | \`http://127.0.0.1:11434\` | serves both OpenAI- and Anthropic-compatible APIs, so it drives every agent |
| \`lmstudio\` | \`http://127.0.0.1:1234/v1\` | OpenAI-compatible |
| \`llamacpp\` | \`http://127.0.0.1:8080/v1\` | OpenAI-compatible |
| \`vllm\` | \`http://127.0.0.1:8000/v1\` | OpenAI-compatible |

No key is required for any of them.

## Providers anyagent cannot drive

| id | reason |
| --- | --- |
${unsupported.join('\n')}

These authenticate with signed requests or cloud credentials rather than a bearer
token, which a base URL cannot express. Use the vendor's own gateway, or point
anyagent at a proxy that accepts a bearer token with \`--base-url\`.
`;

fs.writeFileSync(path.join(root, 'docs', 'providers.md'), providersDoc);

console.log(
  `docs: agents.md (${AGENTS.length} agents), providers.md (${catalog.providers.length} providers, ` +
    `${anthropicCapable.length} anthropic, ${responsesCapable.length} responses)`,
);
