import path from 'node:path';

import type { Agent, LaunchPlan, PlanContext } from '../types.js';
import { toYaml, type Value } from '../serialize.js';
import { MANAGED_ID, managedDir } from './common.js';

const API_KEY_ENV = 'ANYAGENT_DSH_API_KEY';

/**
 * DeepSeek Harness.
 *
 * Harness supports layering a settings patch on top of the user's own config
 * with `--patch`, which makes this a zero-touch integration: the patch lives in
 * anyagent's state directory and the user's profiles, sessions and credentials
 * are neither read nor modified.
 *
 * The key is passed by *name* (`apiKeyEnv`), never written into the patch file.
 */
export const dsh: Agent = {
  id: 'dsh',
  name: 'DeepSeek Harness',
  description: "DeepSeek's open-source agent harness",
  aliases: ['deepseek-harness'],
  homepage: 'https://github.com/deepseek-ai/deepseek-harness',
  wires: ['openai-chat'],
  bin: ['dsh'],
  install: {
    command: ['npm', 'install', '-g', '@deepseek-ai/dsh'],
    url: 'https://github.com/deepseek-ai/deepseek-harness',
  },

  plan(ctx: PlanContext): LaunchPlan {
    const patchPath = path.join(managedDir(ctx, 'dsh'), 'settings.patch.yaml');
    const passthrough = ctx.passthrough;

    // `dsh web` is the default entry point; an explicit subcommand wins.
    const leading = passthrough[0];
    const args =
      leading && !leading.startsWith('-')
        ? [leading, '--patch', patchPath, ...passthrough.slice(1)]
        : ['web', '--patch', patchPath, ...passthrough];

    return {
      command: { file: 'dsh', args },
      env: { [API_KEY_ENV]: ctx.target.apiKey },
      files: [{ path: patchPath, contents: patch(ctx) }],
      notes: ['Settings are layered with --patch; your dsh profile is untouched.'],
    };
  },

  ownedFiles: (ctx) => [path.join(managedDir(ctx, 'dsh'), 'settings.patch.yaml')],
};

export function patch(ctx: PlanContext): string {
  const { target } = ctx;
  const model: Record<string, Value> = { id: target.model.id };
  if (target.model.contextLimit) model.contextWindow = target.model.contextLimit;
  if (target.model.outputLimit) model.maxTokens = target.model.outputLimit;

  const document: Value = {
    'agent-default-model': { provider: MANAGED_ID, model: target.model.id },
    'llm-pi-ai': {
      providers: {
        [MANAGED_ID]: {
          displayName: `${target.provider.name} (anyagent)`,
          apiKeyEnv: API_KEY_ENV,
          api: 'openai-completions',
          baseURL: target.baseUrl,
          models: [model],
        },
      },
    },
  };
  return `# Generated by anyagent. Layered on top of your dsh settings.\n${toYaml(document)}`;
}
