import path from 'node:path';

import type { Agent, LaunchPlan, PlanContext } from '../types.js';
import { toYaml, type Value } from '../serialize.js';
import { MANAGED_ID, managedDir } from './common.js';

/**
 * Hermes Agent by Nous Research.
 *
 * Hermes configures itself from a YAML file in `HERMES_HOME`. Merging into an
 * existing YAML document would mean parsing - and silently reformatting -
 * config the user wrote by hand, including comments and anchors. Instead
 * anyagent points `HERMES_HOME` at a profile it owns and generates the file
 * from scratch every launch.
 *
 * The trade-off is explicit: an anyagent Hermes session has its own history and
 * settings, and the user's default Hermes profile is never at risk.
 */
export const hermes: Agent = {
  id: 'hermes',
  name: 'Hermes',
  description: 'Self-improving agent by Nous Research',
  homepage: 'https://hermes-agent.nousresearch.com/docs',
  wires: ['openai-chat'],
  bin: ['hermes'],
  install: { url: 'https://hermes-agent.nousresearch.com/docs/getting-started/installation/' },

  plan(ctx: PlanContext): LaunchPlan {
    const home = managedDir(ctx, 'hermes');
    const configFile = path.join(home, 'config.yaml');

    return {
      command: { file: 'hermes', args: [...ctx.passthrough] },
      env: { HERMES_HOME: home },
      files: [{ path: configFile, contents: hermesConfig(ctx), mode: 0o600 }],
      notes: [
        `Hermes runs from an anyagent profile at ${home}.`,
        'Your default ~/.hermes profile and its history are untouched.',
      ],
    };
  },

  ownedFiles: (ctx) => [path.join(managedDir(ctx, 'hermes'), 'config.yaml')],
};

export function hermesConfig(ctx: PlanContext): string {
  const { target } = ctx;
  const config: Value = {
    model: {
      provider: MANAGED_ID,
      default: target.model.id,
      base_url: target.baseUrl,
      api_key: target.apiKey,
    },
    providers: {
      [MANAGED_ID]: {
        name: `${target.provider.name} (anyagent)`,
        api: target.baseUrl,
        default_model: target.model.id,
        models: [target.model.id],
      },
    },
  };
  return `# Generated by anyagent. Edits are overwritten on the next launch.\n${toYaml(config)}`;
}
